import { Agent } from "./types";

export const defaultAgents: Agent[] = [
  {
    id: "komutan",
    name: "KOMUTAN",
    title: "CEO & Lider",
    emoji: "\ud83d\udc51",
    skills: ["Liderlik", "Strateji"],
    color: "#fbbf24",
    stats: { hp: 100, maxHp: 100, xp: 120, level: 4 },
    status: "ready",
    mood: "focused",
    role: "ceo",
    appearance: {
      bodyColor: "#fbbf24",
      hatColor: "#f59e0b",
      eyeStyle: "cool",
      accessory: "crown",
      skinTone: "#fcd9b6",
      outfit: "suit",
    },
    worldPosition: { x: 50, y: 20 },
  },
  {
    id: "merlin",
    name: "MERLIN",
    title: "Bas Mimar",
    emoji: "\ud83e\uddd9",
    skills: ["Mimari", "Sistem"],
    color: "#4ade80",
    stats: { hp: 95, maxHp: 100, xp: 82, level: 3 },
    status: "ready",
    mood: "focused",
    role: "agent",
    appearance: {
      bodyColor: "#4ade80",
      hatColor: "#22c55e",
      eyeStyle: "normal",
      accessory: "wizard-hat",
      skinTone: "#fcd9b6",
      outfit: "robe",
    },
    worldPosition: { x: 20, y: 55 },
  },
  {
    id: "sir-debug",
    name: "SIR DEBUG",
    title: "Savasci Gelistirici",
    emoji: "\u2694\ufe0f",
    skills: ["Kod", "Bug"],
    color: "#60a5fa",
    stats: { hp: 100, maxHp: 100, xp: 67, level: 2 },
    status: "ready",
    mood: "focused",
    role: "agent",
    appearance: {
      bodyColor: "#60a5fa",
      hatColor: "#3b82f6",
      eyeStyle: "angry",
      accessory: "helmet",
      skinTone: "#fcd9b6",
      outfit: "armor",
    },
    worldPosition: { x: 80, y: 55 },
  },
  {
    id: "pixie",
    name: "PIXIE",
    title: "Tasarim Tilkisi",
    emoji: "\ud83e\udd8a",
    skills: ["Tasarim", "UX"],
    color: "#fb923c",
    stats: { hp: 78, maxHp: 100, xp: 91, level: 3 },
    status: "ready",
    mood: "happy",
    role: "agent",
    appearance: {
      bodyColor: "#fb923c",
      hatColor: "#f97316",
      eyeStyle: "happy",
      accessory: "bow",
      skinTone: "#fcd9b6",
      outfit: "dress",
    },
    worldPosition: { x: 35, y: 78 },
  },
  {
    id: "data-x",
    name: "DATA-X",
    title: "Veri Buyucusu",
    emoji: "\ud83d\udd2e",
    skills: ["Veri", "ML"],
    color: "#c084fc",
    stats: { hp: 88, maxHp: 100, xp: 95, level: 3 },
    status: "ready",
    mood: "focused",
    role: "agent",
    appearance: {
      bodyColor: "#c084fc",
      hatColor: "#a855f7",
      eyeStyle: "cool",
      accessory: "crystal",
      skinTone: "#fcd9b6",
      outfit: "lab-coat",
    },
    worldPosition: { x: 65, y: 78 },
  },
];
